Samples:
- BR03_LacZ_repA1_S36
- BR03_LacZ_repA2_S42
- BR03_LacZ_repB1_S37
- BR03_LacZ_repB2_S43
- BR03_MORC2i_repA1_S38
- BR03_MORC2i_repA2_S44
- BR03_MORC2i_repB1_S39
- BR03_MORC2i_repB2_S45
- BR03_TASORi_repA1_S40
- BR03_TASORi_repA2_S46
- BR03_TASORi_repB1_S41
- BR03_TASORi_repB2_S47
- Sai2_MORC2_DNMT1_KD_A_S9
- Sai2_MORC2_DNMT1_KD_B_S10
- Sai2_MORC2_DNMT1_KD_C_S11
- Sai2_MORC2_DNMT1_KD_D_S12
- Sai2_MORC2_DNMT1_LZ_A_S13
- Sai2_MORC2_DNMT1_LZ_B_S14
- Sai2_MORC2_DNMT1_LZ_C_S15
- Sai2_MORC2_DNMT1_LZ_D_S16
- OEK450_hNES_Sai2_LV3599_LACZ_a_S27
- OEK451_hNES_Sai2_LV3599_LACZ_b_S28
- OEK452_hNES_Sai2_LV3599_LACZ_c_S29
- OEK453_hNES_Sai2_LV3599_LACZ_d_S30
- OEK454_hNES_Sai2_LV3800_DNMT1_g1i_a_S31
- OEK455_hNES_Sai2_LV3800_DNMT1_g1i_b_S32
- OEK456_hNES_Sai2_LV3802_DNMT1_g3i_a_S33
- OEK457_hNES_Sai2_LV3802_DNMT1_g3i_b_S34
- control_1
- control_2
- control_3
- dnmt1ko_1
- dnmt1ko_2
- dnmt1ko_3
